app.pix.clientId=Client_Id_5f38e81ec8ebcd5a931cac0b1f2550b03cb3f370
app.pix.clientSecret=Client_Secret_ddfebc9adfb47951ee4ee58111b8b0d775d779b4
app.pix.certificatePath= ./.local/prod/producao-888241-TesteLocal2.p12
app.pix.chavePix=31b007ea-f1f0-48be-a72d-67ed74ddd8d2
app.pix.sandbox=false
app.pix.debug=true
api.security.token.secret=${JWT_SECRET:my-secret-key}